# Site settings
title: Rowan T
email: rowan@thecave.com
description: "Rowan T’s world through the eyes of Mommy and Daddy T."
author: Daddy T
baseurl: ""
url: "http://www.rowanturner.net"
header-img: "img/home-bg.jpg"
twitter_username: rowan_t
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# Set background image count to the number of bg-NN.jpg images.
# This will randomly select a header image when none is specified.
backgroundImageCount: 3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Rakefile"]
include: [".nojekyll"]
