# Site settings
title: Rowan T
email: rowan@thecave.com
description: "Rowan T’s world through the eyes of Mamma and Papa T."
baseurl: ""
url: "http://www.rowanturner.net"
header-img: "img/home-bg.jpg"
twitter_username: rowan_t
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Rakefile"]
